[package]
name = "Macrobot"
version = "0.1.0"
authors = ["Nolan Rosen <nolanrosen15@gmail.com>", "Scott Fasone"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
enigo = "0.0.14"
actix-web = "3.1.0"